# Generated by Django 5.1.3 on 2024-11-22 12:26

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='myself',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
