# Generated by Django 5.1.3 on 2024-11-22 12:54

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_travel_date_alter_blog_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='biography',
            name='profile_img',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='myself',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=blogs.models.get_video_upload_to),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='image_url',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image_url',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
    ]
