# Generated by Django 5.1.3 on 2024-11-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_travel_date_alter_advertisement_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
    ]
