# Generated by Django 5.1.3 on 2024-12-18 04:28

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='biography',
            name='profile_img',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='myself',
            name='video',
            field=models.FileField(upload_to=blogs.models.get_video_upload_to),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='image_url',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image_url',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_to),
        ),
    ]
